name: hanami-view
codacy_id: fe8a45d76d8b45f6a680a29c48b43a99
gemspec:
  authors: ["Tim Riley", "Piotr Solnica"]
  email: ["tim@icelab.com.au", "piotr.solnica@gmail.com"]
  summary: "A complete, standalone view rendering system that gives you everything you need to write well-factored view code"
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [concurrent-ruby, "~> 1.0"]
    - [dry-configurable, "~> 0.1"]
    - [dry-core, "~> 0.2"]
    - [dry-equalizer, "~> 0.2"]
    - [dry-inflector, "~> 0.1"]
    - [tilt, "~> 2.0", ">= 2.0.6"]
